# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RepoMVVM' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RepoMVVM

  target 'RepoMVVMTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RepoMVVMUITests' do
    # Pods for testing
  end

pod 'Kingfisher', '~> 7.0'

end
